sudo: required

language: php

php:
  - 7.2

services:
  - docker

before_script:
  - docker build -t waldo-test-travis .
  - docker run -d waldo-test-travis

script:
  - docker ps | grep -q waldo-test-travis
  - docker exec -it waldo-test-travis vendor/bin/phpunit
